


export const ludia = [
  {
    id: "1",
    klientMeno: "Erik",
    klientPriezvisko: "Elinucni",
    klientMesto: "Luterbach, Švajčiarsko",
    klientDatum: "5.10 2025",
    klientAkoDlho: "Pobyt trval jednu noc",
    klientFotky: "/muz9.avif",
    klientHodnotenieVlaste: "4.54",
    klientHodnotenie:
      "Bývanie bolo asi v najlepšej lokalite akú sme si len mohli vybrať. Komunikácia hostiteľa bola veľmi rýchla. Určite tento byt odporúčam a veľmi rád sa presne vrátim aj na najbližšej návšteve Budapešti.",
  },
  {
    id: "2",
    klientMeno: "Kamil",
    klientPriezvisko: "Elinucni",
    klientMesto: "Bahía Blanca, Argentína",
    klientDatum: "3.9 2025",
    klientAkoDlho: "Pobyt trval jednu noc",
    klientFotky: "/muz8.avif",
    klientHodnotenieVlaste: "4.21",
    klientHodnotenie:
      "Apartmán bol veľmi čistý a pohodlný, lokalita skvelá na prechádzky po centre Paríža.",
  },
  {
    id: "3",
    klientMeno: "Anna",
    klientPriezvisko: "Novakova",
    klientMesto: "Bratislava, Slovensko",
    klientDatum: "23.4 2012",
    klientAkoDlho: "Pobyt trval tri dni",
    klientFotky: "/zena9.avif",
    klientHodnotenieVlaste: "4.80",
    klientHodnotenie:
      "Úžasná hostiteľka, všetko vysvetlila a odporučila miestne reštaurácie.",
  },
  {
    id: "4",
    klientMeno: "Peter",
    klientPriezvisko: "Kovac",
    klientMesto: "Praha, Česká republika",
    klientDatum: "23.5 2012",
    klientAkoDlho: "Pobyt trval päť nocí",
    klientFotky: "/muz5.jpg",
    klientHodnotenieVlaste: "4.52",
    klientHodnotenie:
      "Pekný výhľad na more, pokojná ulica a všetko po ruke.",
  },
  {
    id: "5",
    klientMeno: "Lucia",
    klientPriezvisko: "Horvathova",
    klientMesto: "Viedeň, Rakúsko",
    klientDatum:"29.2 2020",
    klientAkoDlho: "Pobyt trval dva dni",
    klientFotky: "/zena1.jpg",
    klientHodnotenieVlaste: "4.90",
    klientHodnotenie:
      "Byt mal všetko, čo sme potrebovali  kuchyňu, klimatizáciu a rýchly internet.",
  },
  {
    id: "6",
    klientMeno: "Martin",
    klientPriezvisko: "Siska",
    klientMesto: "Kodaň, Dánsko",
    klientDatum: "13.2 2023",
    klientAkoDlho: "Pobyt trval štyri dni",
       klientFotky: "/muz9.avif",
    klientHodnotenieVlaste: "4.70",
    klientHodnotenie:
      "Bývanie bolo blízko stanice metra, ideálne na výlety po Ríme.",
  },
  {
    id: "7",
    klientMeno: "Petra",
    klientPriezvisko: "Mlynarova",
    klientMesto: "Londýn, UK",
    klientDatum: "09.11 2024",
    klientAkoDlho: "Pobyt trval sedem nocí",
       klientFotky: "/muz9.avif",
    klientHodnotenieVlaste: "5.00",
    klientHodnotenie:
      "Veľmi príjemná komunikácia, hostiteľ ochotný a flexibilný s check-inom.",
  },
  {
    id: "8",
    klientMeno: "Filip",
    klientPriezvisko: "Novotny",
    klientMesto: "Paríž, Francúzsko",
    klientDatum: "12.10 2025",
    klientAkoDlho: "Pobyt trval tri dni",
    klientFotky: "/muz9.avif",
    klientHodnotenieVlaste: "4.60",
    klientHodnotenie:
      "Izba mala moderný dizajn a pohodlnú posteľ, presne ako na fotkách.",
  },
  {
    id: "9",
    klientMeno: "Sofia",
    klientPriezvisko: "Kralova",
    klientMesto: "Rím, Taliansko",
    klientDatum:"01.1 2026",
    klientAkoDlho: "Pobyt trval štyri dni",
      klientFotky: "/muz9.avif",
    klientHodnotenieVlaste: "4.85",
    klientHodnotenie:
      "Nádherné ubytovanie, čisté a štýlové. Komunikácia s hostiteľom bola bezproblémová.",
  },
  {
    id: "10",
    klientMeno: "Jakub",
    klientPriezvisko: "Varga",
    klientMesto: "Berlin, Nemecko",
    klientDatum: "24.6 2023",
    klientAkoDlho: "Pobyt trval päť nocí",
klientFotky: "/muz5.jpg",
    klientHodnotenieVlaste: "4.40",
    klientHodnotenie:
      "Pobyt bol príjemný, lokalita veľmi dobrá, hostiteľ veľmi milý.",
  },
  {
    id: "11",
    klientMeno: "Michaela",
    klientPriezvisko: "Farkašova",
    klientMesto: "Amsterdam, Holandsko",
    klientDatum:"13.12 2024",
    klientAkoDlho: "Pobyt trval dva dni",
    klientFotky: "/zena2.jpg",
    klientHodnotenieVlaste: "4.95",
    klientHodnotenie:
      "Apartmán bol perfektne vybavený, kuchyňa mala všetko, čo sme potrebovali.“",
  },
  {
    id: "12",
    klientMeno: "Lukas",
    klientPriezvisko: "Bielik",
    klientMesto: "Oslo, Nórsko",
    klientDatum: "19.2 2023",
    klientAkoDlho: "Pobyt trval štyri dni",
   klientFotky: "/zena3.jpg",
    klientHodnotenieVlaste: "4.70",
    klientHodnotenie:
      "Perfektné miesto pre rodinu s deťmi, v okolí parky a obchody.",
  },
  {
    id: "13",
    klientMeno: "Natália",
    klientPriezvisko: "Molnarova",
    klientMesto: "Lisabon, Portugalsko",
    klientDatum:  "12.4 2024",
    klientAkoDlho: "Pobyt trval päť dní",
     klientFotky: "/muz9.avif",
    klientHodnotenieVlaste: "4.80",
    klientHodnotenie:
      "Skvelé miesto na dovolenku, čisté a komfortné. Hostiteľ veľmi ochotný.",
  },
  {
    id: "14",
    klientMeno: "Tomas",
    klientPriezvisko: "Urban",
    klientMesto: "Madrid, Španielsko",
    klientDatum: "19.6 2022",
    klientAkoDlho: "Pobyt trval tri dni",
klientFotky: "/muz5.jpg",
    klientHodnotenieVlaste: "4.60",
    klientHodnotenie:
      "Bývanie bolo veľmi dobre vybavené a čisté. Lokalita ideálna pre turistov.",
  },
  {
    id: "15",
    klientMeno: "Elena",
    klientPriezvisko: "Kovacova",
    klientMesto: "Dubaj, SAE",
    klientDatum: "28.12 2023",
    klientAkoDlho: "Pobyt trval štyri dni",
    klientFotky: "/zena2.jpg",
    klientHodnotenieVlaste: "5.00",
    klientHodnotenie:
      "Luxusné ubytovanie, perfektne vybavené. Hostiteľ bol veľmi priateľský a ochotný.",
  },
];
